---

- name: create backup crons
  cron:
    name: "{{ item.name }}"
    month: "{{ item.month|default(omit) }}"
    weekday: "{{ item.weekday|default(omit) }}"
    day: "{{ item.day|default(omit) }}"
    hour: "{{ item.hour|default(omit) }}"
    minute: "{{ item.minute|default(omit) }}"
    job: "[ -x /usr/bin/barman ] && /usr/bin/barman -q backup {{ item.server }}"
    state: "{{ item.state|default('present') }}"
    cron_file: barman_server_cron
    user: barman
    backup: yes
  with_items: "{{ pgbarman_backup_cron }}"
