---

- name: configure the PostgreSQL APT key
  apt_key: 
    url: https://www.postgresql.org/media/keys/ACCC4CF8.asc 
    state: present
  become: true

- name: configure the PostgreSQL APT repositories
  apt_repository: 
    repo: "deb http://apt.postgresql.org/pub/repos/apt/ {{ 'xenial' if ansible_distribution_release == 'yakkety' else ansible_distribution_release }}-pgdg main"
    state: present
  become: true

- name: ensure PgBarman is installed
  apt: 
    name: "{{ item }}"
    state: present
    update_cache: yes
    cache_valid_time: 3600
  become: true
  with_items:
    - barman

- name: ensure additional compression utility is installed
  apt: 
    name: "{{ pgbarman_compression }}"
    state: present
    update_cache: yes
    cache_valid_time: 3600
  become: true
  when: pgbarman_compression == 'bzip2' or pgbarman_compression == 'gzip' or pgbarman_compression == 'pigz'